name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  check_and_build:
    name: Check and build codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 18

      - name: Installation
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Unit Tests
        run: yarn test
